// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Pattern = Collections['patterns']['schema']['_output']
export declare const patterns: Pattern[]

export type CaseStudy = Collections['caseStudies']['schema']['_output']
export declare const caseStudies: CaseStudy[]

export type Guide = Collections['guides']['schema']['_output']
export declare const guides: Guide[]
